makefile added
afleksik/split pull request #3
Opened 2023-07-24 17:13 UTC by afleksik

Создал мэйкфайл

2023-07-25 05:02 UTC, justas05 requested changes
Если ты добавляешь только makefile, то надо делать `git add Makefile`, а все остальное здесь лишнее. И сообщение в коммите надо делать в таком формате `add makefile`

2023-07-25 05:02 UTC, justas05 commented on src/main.c
> +	}
А зачем ты это все принес в PR?

2023-07-26 03:10 UTC, justas05 requested changes

2023-07-26 03:10 UTC, justas05 commented on Makefile
> +re: fclean all
В конце делай пустую строку

2023-07-27 08:12 UTC, justas05 requested changes

2023-07-27 08:12 UTC, justas05 commented on Makefile
У тебя сейчас заносится 2 мейкфайла в этом ПРе. Зачем?

2023-07-27 08:12 UTC, justas05 commented on src/get_filename.c
Если ты создаешь ПР, который называется 'add makefile', то надо, чтобы в нем и был только он, а не 5 файлов.

2023-07-27 10:04 UTC, afleksik commented on src/get_filename.c
А как мне добавлять файлы тогда не в ПР? Я добавляю файлы на вторую ветку и они сами добавляются в ПР

2023-07-27 10:05 UTC, afleksik commented on Makefile
Первый должен затереться вторым разве нет?

2023-07-27 12:29 UTC, justas05 commented on src/get_filename.c
Ты должен эти файлы в другой ветке отправлять. И обращай внимание на то, откуда ты делаешь новую ветку.

2023-07-27 12:29 UTC, justas05 commented on Makefile
Они в разных папках

2023-07-27 14:24 UTC, closed without merging